// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockWise.Data;

#nullable disable

namespace StockWise.Migrations
{
    [DbContext(typeof(StockWiseDbContext))]
    [Migration("20260913095040_AddItemBrand")]
    partial class AddItemBrand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockWise.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpiryAfterOpeningDays")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsOpenable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("StockWise.Models.ItemStorageCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("AllowedWhenOpened")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowedWhenUnopened")
                        .HasColumnType("boolean");

                    b.HasKey("ItemId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ItemStorageCategories");
                });

            modelBuilder.Entity("StockWise.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            CategoryId = 1,
                            Name = "Fridge Door"
                        },
                        new
                        {
                            LocationId = 2,
                            CategoryId = 1,
                            Name = "Fridge Shelves"
                        },
                        new
                        {
                            LocationId = 3,
                            CategoryId = 2,
                            Name = "Inside Freezer"
                        },
                        new
                        {
                            LocationId = 4,
                            CategoryId = 2,
                            Name = "Outside Freezer"
                        },
                        new
                        {
                            LocationId = 5,
                            CategoryId = 3,
                            Name = "Drawers"
                        },
                        new
                        {
                            LocationId = 6,
                            CategoryId = 3,
                            Name = "Cereal Cupboard"
                        },
                        new
                        {
                            LocationId = 7,
                            CategoryId = 3,
                            Name = "Cupboard L"
                        },
                        new
                        {
                            LocationId = 8,
                            CategoryId = 3,
                            Name = "Cupboard R"
                        });
                });

            modelBuilder.Entity("StockWise.Models.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("Expiry")
                        .HasColumnType("date");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("StockId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("StockWise.Models.StorageCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("StorageCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Fridge"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Freezer"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Pantry"
                        });
                });

            modelBuilder.Entity("StockWise.Models.ItemStorageCategory", b =>
                {
                    b.HasOne("StockWise.Models.StorageCategory", "Category")
                        .WithMany("ItemStorageCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockWise.Models.Item", "Item")
                        .WithMany("ItemStorageCategories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StockWise.Models.Location", b =>
                {
                    b.HasOne("StockWise.Models.StorageCategory", "Category")
                        .WithMany("Locations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StockWise.Models.Stock", b =>
                {
                    b.HasOne("StockWise.Models.Item", "Item")
                        .WithMany("Stock")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockWise.Models.Location", "Location")
                        .WithMany("Stock")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("StockWise.Models.Item", b =>
                {
                    b.Navigation("ItemStorageCategories");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockWise.Models.Location", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockWise.Models.StorageCategory", b =>
                {
                    b.Navigation("ItemStorageCategories");

                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
